-- MySQL Script generated by MySQL Workbench
-- Thu Mar 12 18:10:50 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

CREATE DATABASE uartifydatabase;
USE ucartifydatabase;

CREATE TABLE ucartifydatabase.users(
    user_id INT PRIMARY KEY IDENTITY (1,1),
    username VARCHAR(45) NOT NULL,
    password VARCHAR(45) NOT NULL
);

CREATE TABLE ucartifydatabase.products(
    product_id INT PRIMARY KEY IDENTITY (1,1),
    name VARCHAR(45) NOT NULL,
    url VARCHAR(45) NOT NULL,
    price DECIMAL(6) NOT NULL
);